name: Terraform CI/CD

on:
  push:
    branches:
      - feature/github-actions-pipeline

  pull_request:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    name: Terraform Plan
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Check Terraform Directory
        shell: bash
        run: |
          echo "Checking Terraform directory..."

          if [ -d "./enviroment/preprod" ]; then
            echo "Terraform directory exists ✅"
            ls -la ./enviroment/preprod
          else
            echo "ERROR: ./enviroment/preprod directory does not exist ❌"
            find . -maxdepth 3 -type d | sort
            exit 1
          fi

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Verify Azure Login
        shell: bash
        run: |
          az account show

      - name: Terraform Init
        working-directory: ./enviroment/preprod
        run: terraform init

      - name: Terraform Format Check
        working-directory: ./enviroment/preprod
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        working-directory: ./enviroment/preprod
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./enviroment/preprod
        run: terraform plan