name: Terraform CI/CD

on:
  push:
    branches:
      - "feature/**"
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: read

env:
  TF_WORKING_DIR: environment/preprod

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        run: |
          az login --service-principal \
            --username "25acc71a-cf92-4cb6-9c88-646878e3b993" \
            --password "${{ secrets.AZURE_CLIENT_SECRET }}" \
            --tenant "bc0de973-fa87-4900-94ad-2ac1ab72d129"

          az account set \
            --subscription "${{ secrets.AZURE_SUBSCRIPTION_ID }}"

      - name: Verify Azure Login
        run: az account show

      - name: Terraform Format
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform fmt -check -recursive

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init

      - name: Terraform Validate
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform validate

      - name: Terraform Plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform plan